name: TravelTickets
main: me.nonit.traveltickets.TravelTickets
version: 0.3.1
description: Tickets to warp!
author: Melonking
softdepend: [Vault]

commands:
  travelticket:
    description: Make a ticket!
    aliases: [ticket,tt]
